# Generated by Django 5.1.1 on 2024-10-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='file',
        ),
        migrations.AlterField(
            model_name='film',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
