# Generated by Django 5.1.1 on 2024-10-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0002_remove_film_file_alter_film_views_alter_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='duration',
        ),
    ]
